#server:
#  port: 8082
#
#spring:
#  h2:
#    console:
#      enabled: true

#keycloak:
#  realm: javatechie
#  auth-server-url: http://localhost:8180
#  resource: springboot-keycloak
#  public-client: true
#  bearer-only: true